# Browser Configuration
browser=chrome

# Timeout Configuration (in seconds)
implicitWait=10
explicitWait=20
pageLoadTimeout=20


# Set these environment variables while passing commands:
# IFS_TEST_URL - Application URL
# IFS_USERNAME - Valid test username
# IFS_PASSWORD - Valid test password
