browser=chrome
url=https://mingle-t20-portal.mingle.inforos.dev.inforcloudsuite.com/v2/INTQAINFOROSV2_AX1
username=inforosqa01@infor.com
password=Nrth~dd4s#kola8
implicitWait=10
explicitWait = 20
pageLoadTimeout=20
